algoritmo "semnome"
// Função :
// Autor :
// Data : 11/04/2024
// Seção de Declarações 
var
A:inteiro
B:inteiro
S:inteiro
M:inteiro
D:REAL
inicio
ESCREVAL("Escreva a var A")
LEIA(A)
ESCREVAL("Escreva a var B")
LEIA(B)
S<-(A+B)
ESCREVAL("A soma é:")
ESCREVAL(S)
M<-(A*B)
ESCREVAL("A multiplicação é:")
ESCREVAL(M)
D<-(A/B)
ESCREVAL("A dvisão é:")
ESCREVAL(D)


fimalgoritmo
