algoritmo "semnome"
// Função :
// Autor :
// Data : 09/04/2024
// Seção de Declarações 
var
A:inteiro
B:inteiro
C:inteiro
s:inteiro
d:real
n:inteiro
inicio
// Seção de Comandos 
ESCREVAL("Digite o Valor A")
LEIA(A)
ESCREVAL("Digite o Valor B")
LEIA(B)
ESCREVAL("Digite o Valor C")
LEIA(C)
ESCREVAL("qual sera o divisor?")
LEIA(n)
s<-A+B+C
d <- s / n
ESCREVAL("a soma é")
ESCREVAL(s)
ESCREVAL("a média aritmética é")
ESCREVAL(d)


fimalgoritmo
