algoritmo "semnome"
// Função :
// Autor :
// Data : 11/04/2024
// Seção de Declarações 
var
A:caracter
N3:inteiro
N2:inteiro
N1:inteiro
M:real
D:real
inicio
// Seção de Comandos
ESCREVAL("Qual seu nome?")
LEIA(A)
ESCREVAL("Tirou quanto na primeira prova?")
LEIA(N1)
ESCREVAL("E na segunda?")
LEIA(N2)
ESCREVAL("E por ultimo a terceira")
LEIA(N3)
LIMPATELA
ESCREVAL(A)
ESCREVAL("A media do aluno é:")
M<-(N1+N2+N3)
D<-(M/3)
ESCREVAL(D)



fimalgoritmo
